# site settings
title: Welcome to Linh&#39;s website
subtitle: Powered by Jekyll
email: linh@remerge.io
description: Just a website
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Linh Ha
street_address: 345 Kang Ching Road
city: Singapore
state: Singapore
zip_code: 610345
country: Singapore
phone: 90994109

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
facebook_url: https://www.facebook.com/fuurin
github_url: https://github.com/linhremerge
instagram_url: https://instagram.com/fuulyn
linkedin_url: https://www.linkedin.com/in/linhhatt

# build settings
markdown: kramdown

sass:
  style: compressed
